#!/bin/sh
#
# @name trizd1250 hexacopter
#
# @type Quadrotor Wide
#
# @maintainer Jinming Zhang <15651882638@163.com>
#

. ${R}etc/init.d/rc.mc_defaults

param set-default MAV_TYPE 13

# param set-default SYS_CTRL_ALLOC 1

param set-default MC_PITCHRATE_P 0.246
param set-default MC_PITCHRATE_I 0.333
param set-default MC_PITCHRATE_D 0.0096
param set-default MC_PITCH_P 3.88
param set-default MC_ROLLRATE_P 0.18
param set-default MC_ROLLRATE_I 0.252
param set-default MC_ROLLRATE_D 0.0055
param set-default MC_ROLL_P 5.30
param set-default MC_YAWRATE_P 0.18
param set-default MC_YAWRATE_I 0.19
param set-default MC_YAWRATE_D 0.01
param set-default MC_YAW_P 5.45

param set-default MPC_XY_VEL_I_ACC 4
param set-default MPC_XY_VEL_P_ACC 3

param set-default RTL_DESCEND_ALT 10
param set-default RTL_LAND_DELAY 0

param set-default TRIG_INTERFACE 3
param set-default TRIG_MODE 4
param set-default MNT_MODE_IN 0
param set-default MAV_PROTO_VER 2

param set-default CA_AIRFRAME 0
param set-default CA_ROTOR_COUNT 6

param set-default CA_ROTOR0_PX 0.63
param set-default CA_ROTOR0_PY 0.0
param set-default CA_ROTOR0_KM -0.05

param set-default CA_ROTOR1_PX -0.315
param set-default CA_ROTOR1_PY 0.0
param set-default CA_ROTOR1_KM 0.05

param set-default CA_ROTOR2_PX -0.315
param set-default CA_ROTOR2_PY -0.546
param set-default CA_ROTOR2_KM -0.05

param set-default CA_ROTOR3_PX 0.315
param set-default CA_ROTOR3_PY 0.273
param set-default CA_ROTOR3_KM 0.05

param set-default CA_ROTOR4_PX 0.315
param set-default CA_ROTOR4_PY -0.273
param set-default CA_ROTOR4_KM 0.05

param set-default CA_ROTOR5_PX -0.315
param set-default CA_ROTOR5_PY 0.546
param set-default CA_ROTOR5_KM -0.05
