#!/bin/sh
#
# @name TLJZ 30kg with Bottom and Side Motors
#
# @type Dodecarotor cox
# @class Copter
#
#
# @board bitcraze_crazyflie exclude
# @board px4_fmu-v2 exclude
#

. ${R}etc/init.d/rc.mc_defaults

# param set-default NAV_ACC_RAD 2

# param set-default RTL_DESCEND_ALT 10
# param set-default RTL_RETURN_ALT 30


param set-default CA_ROTOR_COUNT 6

# PID params
# param set-default MC_PITCHRATE_P 0.171
# param set-default MC_PITCHRATE_I 0.230
# param set-default MC_PITCHRATE_D 0.0043
#
# param set-default MC_ROLLRATE_P 0.226
# param set-default MC_ROLLRATE_I 0.307
# param set-default MC_ROLLRATE_D 0.0053
#
# param set-default MC_YAWRATE_P 0.16
# param set-default MC_YAWRATE_I 0.17
# param set-default MC_YAWRATE_D 0.0
param set-default MC_PITCHRATE_P 0.169
param set-default MC_PITCHRATE_I 0.229
param set-default MC_PITCHRATE_D 0.0042
param set-default MC_PITCH_P 5.56
param set-default MC_ROLLRATE_P 0.18
param set-default MC_ROLLRATE_I 0.246
param set-default MC_ROLLRATE_D 0.0045
param set-default MC_ROLL_P 5.31
param set-default MC_YAWRATE_P 0.16
param set-default MC_YAWRATE_I 0.17
param set-default MC_YAWRATE_D 0.0
param set-default MC_YAW_P 6.1


# Bottom motors
param set-default CA_ROTOR0_PX 0.195
param set-default CA_ROTOR0_PY 0
param set-default CA_ROTOR0_PZ 0
param set-default CA_ROTOR0_KM -0.05

param set-default CA_ROTOR1_PX -0.195
param set-default CA_ROTOR1_PY 0
param set-default CA_ROTOR1_PZ 0

param set-default CA_ROTOR2_PX 0
param set-default CA_ROTOR2_PY -0.145
param set-default CA_ROTOR2_PZ 0
param set-default CA_ROTOR2_KM -0.05

param set-default CA_ROTOR3_PX 0
param set-default CA_ROTOR3_PY 0.43
param set-default CA_ROTOR3_PZ 0

param set-default CA_ROTOR4_PX 0
param set-default CA_ROTOR4_PY -0.43
param set-default CA_ROTOR4_PZ 0

param set-default CA_ROTOR5_PX 0
param set-default CA_ROTOR5_PY 0.145
param set-default CA_ROTOR5_PZ 0
param set-default CA_ROTOR5_KM -0.05

# Side motors
# param set-default CA_ROTOR6_PX 0.2
# param set-default CA_ROTOR6_PY -0.12
# param set-default CA_ROTOR6_PZ 0
# param set-default CA_ROTOR6_AX 0
# param set-default CA_ROTOR6_AY 1.0000
# param set-default CA_ROTOR6_AZ 0
# param set-default CA_ROTOR6_KM -0.02
# param set-default CA_ROTOR6_CT 1.5
#
# param set-default CA_ROTOR7_PX -0.16
# param set-default CA_ROTOR7_PY 0.4
# param set-default CA_ROTOR7_PZ 0.0
# param set-default CA_ROTOR7_AX 0.0
# param set-default CA_ROTOR7_AY -1.0000
# param set-default CA_ROTOR7_AZ 0.0000
# param set-default CA_ROTOR7_KM 0.02
# param set-default CA_ROTOR7_CT 1.5
#
# param set-default CA_ROTOR8_PX 0.2
# param set-default CA_ROTOR8_PY 0.12
# param set-default CA_ROTOR8_PZ 0
# param set-default CA_ROTOR8_AX 0.0000
# param set-default CA_ROTOR8_AY -1.0000
# param set-default CA_ROTOR8_AZ 0.0000
# param set-default CA_ROTOR8_KM -0.02
# param set-default CA_ROTOR8_CT 1.5
#
# param set-default CA_ROTOR9_PX -0.16
# param set-default CA_ROTOR9_PY -0.4
# param set-default CA_ROTOR9_PZ 0
# param set-default CA_ROTOR9_AX 0.0000
# param set-default CA_ROTOR9_AY 1.0000
# param set-default CA_ROTOR9_AZ 0.0000
# param set-default CA_ROTOR9_KM 0.02
# param set-default CA_ROTOR9_CT 1.5
#
# param set-default CA_ROTOR10_PX 0.1
# param set-default CA_ROTOR10_PY -0.35
# param set-default CA_ROTOR10_PZ 0
# param set-default CA_ROTOR10_AX 0.0000
# param set-default CA_ROTOR10_AY 1.0000
# param set-default CA_ROTOR10_AZ 0.0000
# param set-default CA_ROTOR10_KM -0.02
# param set-default CA_ROTOR10_CT 1.5
#
# param set-default CA_ROTOR11_PX 0.1
# param set-default CA_ROTOR11_PY 0.35
# param set-default CA_ROTOR11_PZ 0
# param set-default CA_ROTOR11_AX 0.0000
# param set-default CA_ROTOR11_AY -1.0000
# param set-default CA_ROTOR11_AZ 0.0000
# param set-default CA_ROTOR11_KM -0.02
# param set-default CA_ROTOR11_CT 1.5


