#!/bin/sh
#
# @name TLJZ 30kg with Bottom and Side Motors
#
# @type Dodecarotor cox
# @class Copter
#
#
# @board bitcraze_crazyflie exclude
# @board px4_fmu-v2 exclude
#

. ${R}etc/init.d/rc.mc_defaults

# param set-default NAV_ACC_RAD 2

# param set-default RTL_DESCEND_ALT 10
# param set-default RTL_RETURN_ALT 30


param set-default CA_ROTOR_COUNT 12
# Bottom motors
param set-default CA_ROTOR0_PX 0.195
param set-default CA_ROTOR0_PY 0
param set-default CA_ROTOR0_PZ 0
param set-default CA_ROTOR0_KM -0.05

param set-default CA_ROTOR1_PX -0.195
param set-default CA_ROTOR1_PY 0
param set-default CA_ROTOR1_PZ 0

param set-default CA_ROTOR2_PX 0
param set-default CA_ROTOR2_PY -0.145
param set-default CA_ROTOR2_PZ 0
param set-default CA_ROTOR2_KM -0.05

param set-default CA_ROTOR3_PX 0
param set-default CA_ROTOR3_PY 0.43
param set-default CA_ROTOR3_PZ 0

param set-default CA_ROTOR4_PX 0
param set-default CA_ROTOR4_PY -0.43
param set-default CA_ROTOR4_PZ 0

param set-default CA_ROTOR5_PX 0
param set-default CA_ROTOR5_PY 0.145
param set-default CA_ROTOR5_PZ 0
param set-default CA_ROTOR5_KM -0.05

# Side motors
param set-default CA_ROTOR6_PX 0.27
param set-default CA_ROTOR6_PY -0.14
param set-default CA_ROTOR6_PZ 0
param set-default CA_ROTOR6_AX 0
param set-default CA_ROTOR6_AY 1.0000
param set-default CA_ROTOR6_AZ 0
param set-default CA_ROTOR6_KM -0.0
param set-default CA_ROTOR6_CT 5

param set-default CA_ROTOR7_PX -0.11
param set-default CA_ROTOR7_PY 0.43
param set-default CA_ROTOR7_PZ 0.0
param set-default CA_ROTOR7_AX 0.0
param set-default CA_ROTOR7_AY -1.0000
param set-default CA_ROTOR7_AZ 0.0000
param set-default CA_ROTOR7_KM 0.0
param set-default CA_ROTOR7_CT 5

param set-default CA_ROTOR8_PX 0.27
param set-default CA_ROTOR8_PY 0.14
param set-default CA_ROTOR8_PZ 0
param set-default CA_ROTOR8_AX 0.0000
param set-default CA_ROTOR8_AY -1.0000
param set-default CA_ROTOR8_AZ 0.0000
param set-default CA_ROTOR8_KM -0.0
param set-default CA_ROTOR8_CT 5

param set-default CA_ROTOR9_PX -0.11
param set-default CA_ROTOR9_PY -0.43
param set-default CA_ROTOR9_PZ 0
param set-default CA_ROTOR9_AX 0.0000
param set-default CA_ROTOR9_AY 1.0000
param set-default CA_ROTOR9_AZ 0.0000
param set-default CA_ROTOR9_KM 0.0
param set-default CA_ROTOR9_CT 5

param set-default CA_ROTOR10_PX 0.12
param set-default CA_ROTOR10_PY -0.28
param set-default CA_ROTOR10_PZ 0
param set-default CA_ROTOR10_AX 0.0000
param set-default CA_ROTOR10_AY 1.0000
param set-default CA_ROTOR10_AZ 0.0000
param set-default CA_ROTOR10_KM -0.0
param set-default CA_ROTOR10_CT 5

param set-default CA_ROTOR11_PX 0.12
param set-default CA_ROTOR11_PY 0.28
param set-default CA_ROTOR11_PZ 0
param set-default CA_ROTOR11_AX 0.0000
param set-default CA_ROTOR11_AY -1.0000
param set-default CA_ROTOR11_AZ 0.0000
param set-default CA_ROTOR11_KM -0.0
param set-default CA_ROTOR11_CT 5


